import Link from "next/link";
import {
  ChevronLeft,
  ChevronRight,
  Download,
  Filter,
  Sparkles,
  X,
} from "lucide-react";
import { ScreenShell } from "@/components/shell/screen-shell";
import { Button } from "@/components/ui/button";

const QUOTE_APPROVALS = [
  {
    id: "novalis-logistics",
    initials: "NL",
    customer: "Novalis Logistics",
    scope: "Enterprise Solution",
    generatedDate: "Oct 12, 2023",
    generatedTime: "14:20 PM",
    amount: "$42,500.00",
    confidence: 98,
  },
  {
    id: "aura-studio",
    initials: "AS",
    customer: "Aura Studio",
    scope: "Consulting Phase I",
    generatedDate: "Oct 11, 2023",
    generatedTime: "09:45 AM",
    amount: "$8,200.00",
    confidence: 94,
  },
  {
    id: "meridian-tech",
    initials: "MT",
    customer: "Meridian Tech",
    scope: "Cloud Infrastructure",
    generatedDate: "Oct 10, 2023",
    generatedTime: "17:10 PM",
    amount: "$128,000.00",
    confidence: 72,
  },
  {
    id: "vanguard-group",
    initials: "VG",
    customer: "Vanguard Group",
    scope: "Security Audit",
    generatedDate: "Oct 10, 2023",
    generatedTime: "11:05 AM",
    amount: "$19,450.00",
    confidence: 89,
  },
] as const;

const STATUS_MIX = [
  {
    label: "High Confidence (90%+)",
    value: 65,
    barClassName: "bg-blue-500",
  },
  {
    label: "Moderate Confidence (70-89%)",
    value: 25,
    barClassName: "bg-orange-400",
  },
  {
    label: "Requires Review (<70%)",
    value: 10,
    barClassName: "bg-red-500",
  },
] as const;

function confidenceColor(confidence: number) {
  if (confidence >= 90) {
    return "text-blue-400";
  }
  if (confidence >= 70) {
    return "text-orange-300";
  }
  return "text-red-300";
}

function confidenceTrackColor(confidence: number) {
  if (confidence >= 90) {
    return "bg-blue-500";
  }
  if (confidence >= 70) {
    return "bg-orange-400";
  }
  return "bg-red-500";
}

export default function QuotesPage() {
  return (
    <ScreenShell
      title="Quote Approvals"
      description="Review and validate quotes generated by your precision AI."
      activeTab="quotes"
    >
      <div className="mx-auto w-full max-w-7xl space-y-8">
        <section className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
          <div>
            <div className="mb-2 flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-500">
              <span>Management</span>
              <ChevronRight className="h-3 w-3" />
              <span className="text-sky-300">Pending Approvals</span>
            </div>
            <h2 className="text-3xl font-black tracking-tight text-white">
              Quote Approvals
            </h2>
            <p className="mt-2 max-w-2xl text-sm text-slate-400">
              High-confidence drafts require a single click to finalize while
              lower-confidence quotes are surfaced for deeper review.
            </p>
          </div>
          <div className="flex items-center gap-3 rounded-2xl border border-slate-800 bg-slate-900 px-4 py-3">
            <div className="space-y-0.5">
              <p className="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-500">
                Avg. Accuracy
              </p>
              <p className="text-xl font-black text-sky-300">98.4%</p>
            </div>
            <div className="h-10 w-px bg-slate-800" />
            <div className="space-y-0.5">
              <p className="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-500">
                Pending Approval
              </p>
              <p className="text-xl font-black text-sky-300">12</p>
            </div>
          </div>
        </section>

        <section className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/60">
          <header className="flex flex-col gap-3 border-b border-slate-800 bg-slate-900 p-4 sm:flex-row sm:items-center sm:justify-between">
            <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-slate-300">
              <span className="h-2 w-2 animate-pulse rounded-full bg-emerald-400" />
              Awaiting Verification
            </div>
            <div className="flex flex-wrap items-center gap-2">
              <Button
                variant="outline"
                className="h-8 border-slate-700 bg-slate-950 text-slate-300 hover:bg-slate-800"
              >
                <Filter className="h-3.5 w-3.5" />
                Filter
              </Button>
              <Button
                variant="outline"
                className="h-8 border-slate-700 bg-slate-950 text-slate-300 hover:bg-slate-800"
              >
                <Download className="h-3.5 w-3.5" />
                Export
              </Button>
            </div>
          </header>

          <div className="overflow-x-auto">
            <table className="min-w-full text-left">
              <thead>
                <tr className="border-b border-slate-800 bg-slate-950/40">
                  <th className="px-6 py-3 text-[11px] font-bold uppercase tracking-[0.16em] text-slate-500">
                    Customer Name
                  </th>
                  <th className="px-6 py-3 text-[11px] font-bold uppercase tracking-[0.16em] text-slate-500">
                    Generated Date
                  </th>
                  <th className="px-6 py-3 text-[11px] font-bold uppercase tracking-[0.16em] text-slate-500">
                    Quote Amount
                  </th>
                  <th className="px-6 py-3 text-[11px] font-bold uppercase tracking-[0.16em] text-slate-500">
                    AI Confidence
                  </th>
                  <th className="px-6 py-3 text-right text-[11px] font-bold uppercase tracking-[0.16em] text-slate-500">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800">
                {QUOTE_APPROVALS.map((quote) => (
                  <tr
                    key={quote.id}
                    className="group transition-colors hover:bg-slate-900/50"
                  >
                    <td className="px-6 py-5">
                      <div className="flex items-center gap-3">
                        <div className="flex h-9 w-9 items-center justify-center rounded-full bg-slate-800 text-xs font-bold text-blue-400">
                          {quote.initials}
                        </div>
                        <div>
                          <Link
                            href={`/dashboard/quotes/${quote.id}`}
                            className="text-sm font-bold text-slate-100 underline-offset-4 hover:text-sky-300 hover:underline"
                          >
                            {quote.customer}
                          </Link>
                          <p className="text-xs text-slate-500">{quote.scope}</p>
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-5 text-sm font-medium text-slate-400">
                      {quote.generatedDate}
                      <span className="block text-[10px] text-slate-600">
                        {quote.generatedTime}
                      </span>
                    </td>
                    <td className="px-6 py-5 text-sm font-bold text-slate-200">
                      {quote.amount}
                    </td>
                    <td className="px-6 py-5">
                      <div className="flex items-center gap-2">
                        <div className="h-1.5 w-24 overflow-hidden rounded-full bg-slate-800">
                          <div
                            className={`h-full rounded-full ${confidenceTrackColor(quote.confidence)}`}
                            style={{ width: `${quote.confidence}%` }}
                          />
                        </div>
                        <span
                          className={`text-xs font-bold ${confidenceColor(quote.confidence)}`}
                        >
                          {quote.confidence}%
                        </span>
                      </div>
                    </td>
                    <td className="px-6 py-5">
                      <div className="flex items-center justify-end gap-2 opacity-0 transition-opacity group-hover:opacity-100">
                        <Button size="sm" className="h-9 rounded-lg bg-blue-500 px-4 text-xs font-bold text-white hover:bg-blue-600">
                          Accept
                        </Button>
                        <Button
                          size="icon-sm"
                          variant="destructive"
                          className="h-9 w-9 rounded-lg bg-red-900/30 text-red-400 hover:bg-red-900 hover:text-white"
                        >
                          <X className="h-4 w-4" />
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <footer className="flex items-center justify-between border-t border-slate-800 bg-slate-950 px-4 py-3 text-xs">
            <span className="text-slate-500">Showing 1-4 of 12 pending quotes</span>
            <div className="flex items-center gap-1">
              <Button
                size="icon-sm"
                variant="outline"
                className="h-7 w-7 border-slate-700 bg-slate-900 text-slate-400"
              >
                <ChevronLeft className="h-3.5 w-3.5" />
              </Button>
              <Button size="icon-sm" className="h-7 w-7 bg-sky-600 text-white">
                1
              </Button>
              <Button
                size="icon-sm"
                variant="outline"
                className="h-7 w-7 border-slate-700 bg-slate-900 text-slate-300"
              >
                2
              </Button>
              <Button
                size="icon-sm"
                variant="outline"
                className="h-7 w-7 border-slate-700 bg-slate-900 text-slate-300"
              >
                3
              </Button>
              <Button
                size="icon-sm"
                variant="outline"
                className="h-7 w-7 border-slate-700 bg-slate-900 text-slate-400"
              >
                <ChevronRight className="h-3.5 w-3.5" />
              </Button>
            </div>
          </footer>
        </section>

        <section className="grid grid-cols-1 gap-6 lg:grid-cols-3">
          <article className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-blue-700 to-blue-900 p-8 text-white shadow-xl lg:col-span-2">
            <div className="relative z-10 flex h-full flex-col">
              <h3 className="text-2xl font-black">Precision Intelligence Report</h3>
              <p className="mt-3 max-w-2xl text-sm text-blue-100/85">
                Our AI analysis suggests that 8 pending quotes match recent
                high-performance closures. Bulk approval is recommended to keep
                workflow velocity high.
              </p>
              <Button className="mt-6 w-fit bg-white text-blue-700 hover:bg-blue-50">
                <Sparkles className="h-3.5 w-3.5" />
                Apply AI Recommendations
              </Button>
            </div>
            <div className="pointer-events-none absolute -bottom-12 -right-10 h-64 w-64 rounded-full bg-blue-500/25 blur-3xl" />
          </article>

          <article className="rounded-2xl border border-slate-800 bg-slate-900 p-6">
            <h3 className="text-sm font-bold uppercase tracking-[0.18em] text-slate-500">
              Quote Status Mix
            </h3>
            <div className="mt-6 space-y-5">
              {STATUS_MIX.map((item) => (
                <div key={item.label}>
                  <div className="mb-2 flex items-center justify-between text-xs font-semibold text-slate-300">
                    <span>{item.label}</span>
                    <span>{item.value}%</span>
                  </div>
                  <div className="h-2 overflow-hidden rounded-full bg-slate-800">
                    <div
                      className={`h-full rounded-full ${item.barClassName}`}
                      style={{ width: `${item.value}%` }}
                    />
                  </div>
                </div>
              ))}
            </div>
            <p className="mt-6 text-[11px] italic text-slate-500">
              Distributions calculated based on historical conversion data and
              current market variables.
            </p>
          </article>
        </section>
      </div>
    </ScreenShell>
  );
}
